[package]
name = "directory-monitor"
version = "0.1.0"
edition = "2021"
author = ["Jacob"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.8.0"
walkdir = "2.3.3"
